### ISSUE TITLE
[Feat] Spring 공부 Ch4

### ISSUE THREAD

**Issue by hellozo0** [hellozo0/ServerLabs#10]
## 📌  Feature Issue
스프링 AWS 어쩌구 책 공부~
머스테치로 화면 구성하기

## 📝  To-do
- [ ] 서버 템플릿 엔진과 머스테치 소개
- [ ] 기본페이지 만들기
- [ ] 게시글 등록 화면 만들기   
- [ ] 전체조회 화면 만들기 
- [ ] 게시글 수정, 삭제 화면 만들기
