### ISSUE TITLE
[FEAT] Spring 공부 Ch6

### ISSUE THREAD

**Issue by hellozo0** [hellozo0/ServerLabs#13]
## 📌  Feature Issue

AWS 서버 환경을 만들어보자 - AWS EC2

## 📝  To-do

- [ ] AWS 회원가입
- [ ] EC2 인스턴스 생성하기
- [ ] EC2 서버에 접속하기
- [ ] 아마존 리눅스1 서버 생성 시 꼭 해야할 설정들
